# Data generation configuration
# Job type: Choose between "series" or "classification"
job_type: "classification"

# Output directory for generated data
output_directory: "data"

# Parameters for data generation
maxinc: 1000
maxexc: 1000
n_samples: 3 # n cascades umbenenen

# FPR targets (set to null or specify a list of FPRs)
fprs: null

# Number of workers for concurrent processing
max_workers: 6

# Padding configuration for deep learning model dataset generation
# Set to true for constant number of cascades and lengths (suitable for deep learning models)
# Set to false for raw data without padding
padding: true

# Collect duration of cascade generation
collect_duration: true
